laser_filter_node:
  ros__parameters:
    scan_filter_chain:
      - 
        name: 'narrow_fov_filter'
        type: 'laser_filters/LaserScanAngularBoundsFilter'
        params:
          angle_min: -0.5236   # -30 degrees in radians
          angle_max: 0.5236    # 30 degrees in radians
